export const MUTATIONS = {
  SIGN_IN:         'sign-in',
  REGISTER:        'register',
  GOOGLE_LOGIN:    'google-login',
  PHONE_LOGIN:     'phone-login',
  LOGOUT:          'logout',
  UPDATE_PROFILE:  'update-profile',
  ADD_EMAIL:       'add-email',
  RESEND_VERIFICATION: 'resend-verification',
  PHONE_CONFIRM:   'phone-confirm',
  DELETE_ACCOUNT:  'delete-account',
  RESET_REQUEST:   'reset-request',
  RESET_CONFIRM:          'reset-confirm',
  ADD_FAVORITE:           'add-favorite',
  REMOVE_FAVORITE:        'remove-favorite',
  BULK_REMOVE_FAVORITES:  'bulk-remove-favorites',
  CREATE_SUBSCRIPTION:    'create-subscription',
  UPDATE_SUBSCRIPTION:    'update-subscription',
  DELETE_SUBSCRIPTION:    'delete-subscription',
  PAUSE_SUBSCRIPTION:     'pause-subscription',
  MARK_SEEN_SUBSCRIPTION: 'mark-seen-subscription',
} as const;
export type MutationType = typeof MUTATIONS[keyof typeof MUTATIONS];
