import {ROUTES} from "@/shared/const/routes";
export const PROTECTED_ROUTES: string[] = [ROUTES.FAVORITES, ROUTES.VIEWED, ROUTES.PROPERTY, ROUTES.SUBSCRIPTIONS, ROUTES.COMPARE, ROUTES.PROFILE]
export const PROTECTED_REDIRECT_ROUTE = ROUTES.SIGN_IN
export const AUTH_REDIRECT_ROUTE = ROUTES.ROOT
export const AUTH_ROUTES: string[] = [ROUTES.SIGN_IN, ROUTES.SIGN_IN_PHONE, ROUTES.REGISTER]